# Generated by Django 3.2.5 on 2022-02-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='-')),
                ('webex_link', models.URLField(blank=True, null=True)),
                ('youtube_live_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='-')),
                ('webex_link', models.URLField(blank=True, null=True)),
                ('youtube_live_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
