# Generated by Django 3.2.5 on 2022-02-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220225_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
