# Generated by Django 3.2.5 on 2022-02-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220225_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
