# Generated by Django 3.2.5 on 2022-03-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='webex_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='paperpresentation',
            old_name='webex_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='youtube_live_link',
        ),
        migrations.RemoveField(
            model_name='paperpresentation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paperpresentation',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='paperpresentation',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='paperpresentation',
            name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='paperpresentation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paperpresentation',
            name='youtube_live_link',
        ),
    ]
